### ISSUE TITLE
SOMA 32to8km and 32to4km test cases are broken

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#233]
As mentioned here:
https://github.com/MPAS-Dev/MPAS-Model/pull/229#issuecomment-489609900
The following SOMA test cases appear to be broken, making it hard to assess their readiness for #229 

* `-o ocean -c soma -r 32km -t time_varying_wind` missing config files for init1, etc.
* `-o ocean -c soma -r 4km -t 32to4km` and `-r 8km -t 32to8km` incomplete config files for inti1, maybe others
* `-o ocean -c soma -r 4km -t 3layer` , `-t default` and `-t surface_restoring` bad permissions on base mesh on LANL IC:
```
-rw-rw----  1 zhendong zhendong 554M Dec  9  2016 SOMA_4km_grid.161202.nc
```
The last is easy to address (and I have asked @caozd999 to do so) and may mean that the test cases at 4km resolution other than `32to4km` are fine once I can read the base mesh.

**Comment by pwolfram** [comment]
@sbrus89, can you please address the issue with `time_varying_wind` as this is your test case?  I'm guessing this is something simple.

@xylar, thanks for following up on these issues.

**Comment by xylar** [comment]
@pwolfram and @sbrus89, let me know if you don't see the problems I'm seeing or if you need more details.

**Comment by sbrus89** [comment]
@xylar, if you could provide some more details, that would be helpful. I've been looking into it, but things seem to work on my end.

**Comment by xylar** [comment]
Okay, will do. I'm on my way home.

**Comment by xylar** [comment]
Sorry, it looks like these test are failing in my tests because of changes in #229.  I'll close this as soon as I can verify this for all the test cases but please don't worry about this for now.

**Comment by sbrus89** [comment]
No problem, let me know if anything comes up!

**Comment by pwolfram** [comment]
Thanks @xylar

**Comment by caozd999** [comment]
I have changed the groups of the two files to climate. Let me know if it
doesn't work.

**Comment by xylar** [comment]
Thanks very much, @caozd999!

@sbrus89, you're definitely off the hook.  The problems with `time_varying_wind` are on my side, not yours.

@pwolfram, I'm working on the other cases now but I suspect the answers will be similar.  Again, sorry for the false alarm.

**Comment by xylar** [comment]
@pwolfram, the 32to4 and 32to8 test cases refer to `MpasMeshGenerator.sh`, which isn't a thing anymore (https://github.com/MPAS-Dev/MPAS-Model/pull/74#issuecomment-420287631).
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/soma/4km/32to4km/config_init1.xml#L53
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/soma/8km/32to8km/config_init1.xml#L53

So those 2 do appear to need to be fixed.  If you want me to include the fix in #229, just let me know what it should be.

**Comment by xylar** [comment]
@pwolfram, the other tests appear to be fine now that @caozd999 has given us permission to read the mesh file.

**Comment by xylar** [comment]
In my testing, I see that these test cases are still broken.

**Comment by xylar** [comment]
@pwolfram, can you please put fixing these two broken test cases on your to-do list somewhere?  The fact that they don't set up makes it hard for us to test whether COMPASS changes have broken existing test cases.

**Comment by xylar** [comment]
@pwolfram, alternatively, can we remove these test cases for now and add them back in the future once they are working again?

**Comment by pwolfram** [comment]
On the previous commit, it looks like a file was deleted in MPAS-Tools before this work was done which made the case break (see copy from https://github.com/MPAS-Dev/MPAS-Model/pull/74#issuecomment-420287631):

"
@mark-petersen, MpasMeshGenerator.sh was from the previous workflow and pointed to https://github.com/MPAS-Dev/MPAS-Tools/blob/master/mesh_tools/triangle_jigsaw_to_netcdf/build_mesh.sh. This was the previous way I built meshes with JIGSAW for the Q2 workflow. I thing we should delete this once we migrate the SOMA 32to4 and 32to8 cases over to the new system because it isn't in use anywhere else.
"

I recommend putting that file back in the meantime until this can be resolved as the reason this test case fails is because a file was deleted without checking back here in `MPAS-Tools`.  Alternatively, that file could also be copied here too.

cc @mark-petersen for ideas too.  We may also be able to just use existing tools to replicate this behavior for the resolution refinement disk in this case too, which is probably a better option.

I unfortunately cannot get to it this week and am not in favor of removing the test case, especially since it was used for a BER deliverable a few years ago.

**Comment by xylar** [comment]
As we discussed on Slack, this won't be as simple as reverting back to a previous workflow, since we really don't support JIGSAW-Matlab anymore.  However, I've marked these test cases as "broken" by moving them to a "broken" subdirectory in #514

**Comment by xylar** [comment]
Closing because this will not be fixed here
