### ISSUE TITLE
Compass conda environment error

### ISSUE THREAD

**Issue by sbrus89** [MPAS-Dev/MPAS-Model#471]
@xylar, when I do 
`source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/load_latest_compass.sh` 

and run the `base_mesh` case for 
`-o ocean -c global_ocean -r CUSP12 -t init` 

I get an error 
`/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/bin/python: No module named numpy`

This is strange because `conda list` shows `numpy` as a package 

This is probably something I'm doing wrong, but was hoping you would be able to help me sort it out.

**Comment by xylar** [comment]
The shebang looks fine, so that's not it:
https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/global_ocean/CUSP12/init/define_base_mesh.py#L1

It looks like you're running with the python in the base environment, not in the compass environment.  Maybe the `conda activate comapss_0.1.2` failed?  If so, can you see what the error message is?

**Comment by xylar** [comment]
I bet you're trying to load the old non-existant `load_compass.sh` instead of `load_latest_compass.sh` or trying to load `compass_py3.7` (also gone).

**Comment by xylar** [comment]
@sbrus89, have you had a chance to try to figure this one out?

**Comment by sbrus89** [comment]
@xylar, I'm going to close this because I haven't been able to reproduce the error since. Thanks for your help.
