### ISSUE TITLE
Automatic population of submodules

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Model#500]
As part of the build process, I would propose we automatically initialize submodules, e.g., for CVmix to not require an explicit call of the form: `git submodule update --init --recursive` in `ocean\develop`.  This will enable similar behavior as to what we had previously and make builds simpler.

**Comment by philipwjones** [comment]
One of the reasons we had the earlier hand-rolled scripts was to avoid any unnecessary git updates in the middle of the build since it can require a password entry, either for git itself or on some machines, to access the ssh key file. That will stall the build if you're running in the background or walk away for a bit and the prompt can get buried in all the build output.

The current build does something similar to the old scripts. There is a check to see if the update has happened and prints a pretty informative error msg if there has been no download. You could always insert the git command at that point instead of printing an error message. But again, it requires some attentiveness during the build to notice a password prompt if needed or in the case of git failure to understand what happened.

Don't have a strong opinion either way. For E3SM builds, you're still going to need the explicit git command since there are many other submodules scattered about.

**Comment by pwolfram** [comment]
Also, when you are developing you'll get a meaningless git status notation of 
`modified:   src/core_ocean/cvmix (untracked content)`
which is completely unnecessary because no editing of note was done to cvmix.

Minimally, we should modify `.gitignore` so we don't have this problem because cvmix is its own repo.

**Comment by xylar** [comment]
@pwolfram, I have no objection to you making these changes.

**Comment by xylar** [comment]
To address @philipwjones' comment about having to enter passwords, it would be best if the `git submodule` call happens immediately at the beginning of the build and only after checking if it is really necessary.

**Comment by pwolfram** [comment]
@philipwjones, am I understanding that the key thing here is to have a clean crash as opposed to a hang when building automatically to prevent issues with needing a password, etc?  This would be for testing, production systems, etc.

If there isn't a clean way too work around this in software, which isn't currently obvious to me if it exists, I can just close the issue.

**Comment by philipwjones** [comment]
@pwolfram Yes, that's correct. Even if there's away for it to time out and bail, that would be preferable to an indefinite hang. I'm still open to solutions to make this work, but I don't currently have any good ideas either.

**Comment by philipwjones** [comment]
And we shouldn't forget your other point - we need to add the right info to gitignore for cvmix. Still reporting as untracked...

**Comment by pwolfram** [comment]
Solution is `git config submodule.src/core_ocean/cvmix.ignore untracked` @philipwjones .  This modifies `.git/config` to

```
...
17 [submodule "src/core_ocean/cvmix"]
18   url = git@github.com:CVMix/CVMix-src.git
19   ignore = untracked                              
```

but, it seems like this is a local setting for a single repo.  No clear `.gitignore` type solution from my query: https://stackoverflow.com/questions/7912022/do-you-ignore-a-git-submodule-in-your-gitignore-or-commit-it-to-your-repo

**Comment by pwolfram** [comment]
@jonbob and @maltrud, the same issue isn't showing up for the BGC repo.  Do you recall how you got the "untracked" `git status` result for it turned off for that repo?  There is no `ignore = untracked` in the `.git/config` file, which makes this even more confusing.

**Comment by jonbob** [comment]
@pwolfram - I don't remember anything different being done for the BGC repo, but @mark-petersen made that commit. You can check the original PR -- [#3507](https://github.com/E3SM-Project/E3SM/pull/3507). Maybe it's just because cvmix is first and the untracked error gets tripped and it doesn't look for the second occurrence? Just a guess....

**Comment by pwolfram** [comment]
Hi Everyone, Please see PR #591 -- We can use a timeout and two separate checks to help facilitate this process . The intention is #591 will close this issue.

**Comment by pwolfram** [comment]
I think this mostly was an irritant to me, so I'll close for now.
