### ISSUE TITLE
COMPASS space for depricated or unsupported test cases

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Model#516]
We have 100 ocean test cases in COMPASS.  This is impossibly many to try to maintain.  Some are there purely for documentary purposes and will only work with earlier configurations of COMPASS.

It would be nice to have a place for old test cases so they don't get deleted but where they are not part of our regular testing.

Suggestions are welcome!

**Comment by xylar** [comment]
@pwolfram and @mark-petersen, this particularly applies to you.  @sbrus89 and @cao999, you may also be interested in this discussion.  @matthewhoffman, something similar may be needed sooner or later for the landice side.

**Comment by xylar** [comment]
One suggestion I had that I don't think is fantastic was to create a new component next to `ocean` called `ocean_depricated` or something like that.  Test cases in this new component would be numbered after those in `ocean` because of how COMPASS orders the test cases, making it easy to build (and test) only those test cases that are actively supported in `ocean`.

**Comment by pwolfram** [comment]
@xylar, did the `broken` tag work for you?  Are these cases getting skipped or are still numbered listing cases?

**Comment by xylar** [comment]
@pwolfram, that worked.  We could mark other test cases as "broken" or "depricated" by moving them into subdirectories with those names as an alternative solution.

**Comment by pwolfram** [comment]
Thanks, sounds like our solution yesterday was "ok" but better options like the above may exist.  Your idea above will allow us to deploy cases for testing more effectively, which is a plus.  It would also highlight different things we could have folks learning MPAS-O do, e.g., summer students, new contributors, etc.  Refractoring a test case with known physics is a low risk activity and for someone starting out would help them learn quickly so that everyone wins.

**Comment by xylar** [comment]
This is being partially addressed by deleting some unused test cases in #530.

**Comment by xylar** [comment]
Closing because no test cases seem to fit this category, as discussed in #530
