### ISSUE TITLE
Print & write statements in PIO lib don't produce output

### ISSUE THREAD

**Issue by cponder** [MPAS-Dev/MPAS-Model#609]
I'm trying to debug an issue where MPAS-A dies inside the UCX communication.
I've been able to insert debug statements into the MPAS-A source using the convention
```
call mpas_log_write('Debug checkpoint 2')
```
Going down into the PIO calls, though, none of these write statements are producing any output:
```
write(6,*) "Debug checkpoint 2.1"
write(0,*) "Debug checkpoint 2.1"
write(OUTPUT_UNIT,*) "Debug 2.0 (output)"
write(ERROR_UNIT,*) "Debug 2.0 (output)"
```
I suspect that MPAS is re-mapping these output channels so the strings don't go anywhere.
Can you tell me what output units would work for C & Fortran? What unit is `mpas_log_write` using?

I can provide the compiler & lib versions, but I don't think they are important to answering the question. If your recommended I/O units don't work, I'll follow up.

**Comment by cponder** [comment]
I tried posting with the MPAS-A developers forum
[](https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=64&t=9280&p=17353#p17353)
but haven't gotten any response from there.

**Comment by mgduda** [comment]
I did post a [response](https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=64&t=9280) in the forum yesterday. It's possible the forum didn't send you a reply notification, or if it did, the notification may have ended up in your spam folder. Since this isn't an issue with the MPAS-Model code itself, I'd suggest we discuss on the forum.
