### ISSUE TITLE
Ocean RK4 fails bfb restart test

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Model#777]
Testing e4dbf57d2 on branch `ocean/develop`, and compass test `ocean/global_ocean/QU240/restart_test` but with flags changed to:
```
 24 &time_integration
 25     config_dt = '00:10:00'
 26     config_time_integrator = 'RK4'
```
the bfb comparison fails. I also turned off surface fluxes, surface restoring, and set to fixed vertical layers, and problem persists, i.e.:
```
config_vert_coord_movement = 'fixed'
config_use_bulk_wind_stress = .false.
config_use_activeTracers_surface_bulk_forcing = .false.
config_use_activeTracers_surface_restoring = .false.
```
This changes the mismatch from 1e-4 to 1e-15. So main problem appears to be in the tracer time stepping:
```
    config_disable_thick_all_tend = .false.
    config_disable_vel_all_tend = .false.
    config_disable_tr_all_tend = .true.
```

Note that the split explicit passes bfb restarts. Tendency routines are identical for split explicit and RK4. RK4 passes partition test, so this is not a halo update problem.

**Comment by mark-petersen** [comment]
@xylar thanks for pointing this out. I tried the easy things that came to mind, as noted in the first comment. I was hoping to find some option that required an update within the split-explicit module, that was not added to RK4. Surface fluxes and forcing are obvious candidates, but do not appear to be related.

**Comment by xylar** [comment]
Thanks @mark-petersen!  As I mentioned at Coffee today, I'm seeing this problem as well in COMPASS 1.0.  Given that some of the wetting-and-drying work will begin with RK4, it would be really helpful if we can track this down and fix it.

cc @dengwirda and @cbegeman

**Comment by mark-petersen** [comment]
OK, I found the module (at least). If I turn off GM:
```
 70 &GM_eddy_parameterization
 71     config_use_GM = .false.
 72     config_GM_closure = 'EdenGreatbatch'
```
Then I get an exact bfb match on restart. I flipped every other flag possible - cvmix, redi, tracer vmix, bottom drag, etc, and GM is definitely the problem. We just added this `EdenGreatbatch` method last fall. Maybe that is it.

**Comment by cbegeman** [comment]
I was looking at GM as well because `ocn_gm_compute_Bolus_velocity` is commented out in the split routine whereas it is called in RK4. This change is associated with https://github.com/MPAS-Dev/MPAS-Model/commit/66a13d9734a942d5c52dd70e9042319599c53bf1, which is supposed to fix a restart problem. Maybe RK4 is redundantly computing MLD rather than using its value for restart. @vanroekel might understand this better than I do.

**Comment by vanroekel** [comment]
@mark-petersen does the test pass with 
```
config_use_GM = .true.
config_GM_closure = 'constant'
```
?

If the problem is E&G it suggests RK4 is not calling the routine that computes ```BruntVaisalaFreqTop``` or ```RiTopOfCell``` on restart

@cbegeman just saw your comment and checked the rk4 code, you are right!  The calls here

https://github.com/MPAS-Dev/MPAS-Model/blob/master/src/core_ocean/mode_forward/mpas_ocn_time_integration_rk4.F#L648-L650

and

https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/src/core_ocean/mode_forward/mpas_ocn_time_integration_rk4.F#L1248-L1251

should not be there.  This routine is called here now instead

https://github.com/MPAS-Dev/MPAS-Model/blob/master/src/core_ocean/mode_forward/mpas_ocn_time_integration_rk4.F#L648-L650

It's not clear to me why this causes a restart BFB.  The MLD is not used in the GM code, just Redi.  I'll think about it some more.

**Comment by cbegeman** [comment]
@vanroekel Thanks! Your first and last links appear to be the same. Should the last link be https://github.com/MPAS-Dev/MPAS-Model/blob/e4dbf57d235e0a6bf6c568e2423cafe8091c5486/src/core_ocean/mode_forward/mpas_ocn_forward_mode.F#L576-L578

**Comment by vanroekel** [comment]
oops, yes, thanks for catching that!  I've edited my previous comment

**Comment by mark-petersen** [comment]
With `config_use_GM` true the restart test always fails, with both `config_GM_closure = 'constant'` and `'EdenGreatbatch'`. I only get the test to pass with `config_use_GM = .false.`.

**Comment by vanroekel** [comment]
Okay I think I understand what is happening.  To confirm, @mark-petersen is redi enabled for these runs with standard options ```config_Redi_use_surface_taper = .true.``` and ```config_use_redi=.true.```?  If so the code blocks mentioned above, in particular the if(config_use_GM) lines imply that the surface taper is recomputed during the timestep and not using the indMLD from the restart file.  I would suspect a test with ```config_use_redi=.false.``` and ```config_use_GM=.true.```, but your last comment suggests you have tried this?  If so I'm wrong.  But I would also try with deleting the two blocks of code I mention above.

**Comment by xylar** [comment]
@mark-petersen and @vanroekel I realize this is a low priority but I want to make sure it gets some attention because I see this error several times a day when I work with compass, and it increases the likelihood that a "real" error happens that I don't notice.  Also, the lack of restart capability means that the RK4 time integrator isn't really a feasible alternative to split-explicit except for tests short enough not to need restart.

**Comment by mark-petersen** [comment]
Transplanted this issue to https://github.com/E3SM-Project/E3SM/issues/4376. Fixed by https://github.com/E3SM-Project/E3SM/pull/4369.
